"""Module-level shortcut for every endpoint.

Generated by ``tools/generate_endpoints.py``. Do not edit.

Endpoints: 67
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .response import Result
from .shortcuts import default_client

__all__ = [
    "almanac",
    "antiscia",
    "aspects",
    "astrocartography",
    "batch",
    "chart",
    "chart_with_custom_body",
    "compatibility",
    "composite",
    "custom_bodies",
    "custom_body",
    "custom_lot",
    "daily",
    "declinations",
    "delete_custom_body",
    "dignities",
    "draconic",
    "eclipses",
    "electional",
    "export_csv",
    "export_pdf",
    "export_report",
    "firdaria",
    "harmonics",
    "health",
    "heliacal",
    "heliocentric",
    "horary",
    "job",
    "list_jobs",
    "lunar_return",
    "mansions",
    "midpoints",
    "moon_phases",
    "moon_phases_for",
    "nakshatra",
    "natal",
    "navamsa",
    "pair_aspects",
    "parans",
    "patterns",
    "profection",
    "progression",
    "query",
    "rectification",
    "render_astrocartography",
    "render_biwheel",
    "render_png",
    "render_sharecard",
    "render_svg",
    "retrogrades",
    "saturn_return",
    "save_custom_body",
    "search_places",
    "solar_arc",
    "solar_return",
    "stations",
    "submit_batch_job",
    "submit_job",
    "synastry",
    "timeline",
    "transit_hits",
    "transits",
    "vedic_chart",
    "vimshottari",
    "void_moon",
    "zodiacal_releasing",
]


def almanac(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Eclipses, retrogrades, planetary hours, and void Moon….

    Forwards to :meth:`AstroMansion.almanac` on the shared client.
    """
    return default_client().almanac(payload, **fields)


def antiscia(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Antiscia and contra-antiscia.

    Forwards to :meth:`AstroMansion.antiscia` on the shared client.
    """
    return default_client().antiscia(payload, **fields)


def aspects(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Complete natal aspect list.

    Forwards to :meth:`AstroMansion.aspects` on the shared client.
    """
    return default_client().aspects(payload, **fields)


def astrocartography(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Astrocartography lines.

    Forwards to :meth:`AstroMansion.astrocartography` on the shared client.
    """
    return default_client().astrocartography(payload, **fields)


def batch(*args: Any, **kwargs: Any) -> Result:
    """Batch computation (Enterprise).

    Forwards to :meth:`AstroMansion.batch` on the shared client.
    """
    return default_client().batch(*args, **kwargs)


def chart(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Extended natal chart with category selection.

    Forwards to :meth:`AstroMansion.chart` on the shared client.
    """
    return default_client().chart(payload, **fields)


def compatibility(
    birth: dict[str, Any], partner: dict[str, Any], **kwargs: Any
) -> Result:
    """Compatibility score from 0 to 100.

    Forwards to :meth:`AstroMansion.compatibility` on the shared client.
    """
    return default_client().compatibility(birth, partner, **kwargs)


def composite(birth: dict[str, Any], partner: dict[str, Any], **kwargs: Any) -> Result:
    """Midpoint composite chart.

    Forwards to :meth:`AstroMansion.composite` on the shared client.
    """
    return default_client().composite(birth, partner, **kwargs)


def custom_body(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Custom elliptic or hyperbolic Keplerian body.

    Forwards to :meth:`AstroMansion.custom_body` on the shared client.
    """
    return default_client().custom_body(payload, **fields)


def custom_bodies(*args: Any, **kwargs: Any) -> Result:
    """List saved custom bodies.

    Forwards to :meth:`AstroMansion.custom_bodies` on the shared client.
    """
    return default_client().custom_bodies(*args, **kwargs)


def save_custom_body(*args: Any, **kwargs: Any) -> Result:
    """Save and calculate a named custom Keplerian body.

    Forwards to :meth:`AstroMansion.save_custom_body` on the shared client.
    """
    return default_client().save_custom_body(*args, **kwargs)


def chart_with_custom_body(*args: Any, **kwargs: Any) -> Result:
    """Calculate a saved custom body by name.

    Forwards to :meth:`AstroMansion.chart_with_custom_body` on the shared client.
    """
    return default_client().chart_with_custom_body(*args, **kwargs)


def delete_custom_body(*args: Any, **kwargs: Any) -> Result:
    """Delete a saved custom body.

    Forwards to :meth:`AstroMansion.delete_custom_body` on the shared client.
    """
    return default_client().delete_custom_body(*args, **kwargs)


def custom_lot(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Custom Arabic lot formula (A+B-C).

    Forwards to :meth:`AstroMansion.custom_lot` on the shared client.
    """
    return default_client().custom_lot(payload, **fields)


def daily(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Daily sky summary.

    Forwards to :meth:`AstroMansion.daily` on the shared client.
    """
    return default_client().daily(payload, **fields)


def declinations(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Declination parallels.

    Forwards to :meth:`AstroMansion.declinations` on the shared client.
    """
    return default_client().declinations(payload, **fields)


def dignities(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Classical dignities and almuten.

    Forwards to :meth:`AstroMansion.dignities` on the shared client.
    """
    return default_client().dignities(payload, **fields)


def draconic(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Draconic zodiac.

    Forwards to :meth:`AstroMansion.draconic` on the shared client.
    """
    return default_client().draconic(payload, **fields)


def eclipses(*args: Any, **kwargs: Any) -> Result:
    """Eclipse calendar.

    Forwards to :meth:`AstroMansion.eclipses` on the shared client.
    """
    return default_client().eclipses(*args, **kwargs)


def electional(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Electional date-window scan.

    Forwards to :meth:`AstroMansion.electional` on the shared client.
    """
    return default_client().electional(payload, **fields)


def export_csv(payload: dict[str, Any] | None = None, **fields: Any) -> bytes | Path:
    """Chart data as CSV.

    Forwards to :meth:`AstroMansion.export_csv` on the shared client.
    """
    return default_client().export_csv(payload, **fields)


def export_pdf(payload: dict[str, Any] | None = None, **fields: Any) -> bytes | Path:
    """Multi-page PDF report.

    Forwards to :meth:`AstroMansion.export_pdf` on the shared client.
    """
    return default_client().export_pdf(payload, **fields)


def export_report(*args: Any, **kwargs: Any) -> Result:
    """Editable multi-page PDF report.

    Forwards to :meth:`AstroMansion.export_report` on the shared client.
    """
    return default_client().export_report(*args, **kwargs)


def firdaria(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Firdaria periods.

    Forwards to :meth:`AstroMansion.firdaria` on the shared client.
    """
    return default_client().firdaria(payload, **fields)


def search_places(*args: Any, **kwargs: Any) -> Result:
    """Search place names.

    Forwards to :meth:`AstroMansion.search_places` on the shared client.
    """
    return default_client().search_places(*args, **kwargs)


def harmonics(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Harmonic chart.

    Forwards to :meth:`AstroMansion.harmonics` on the shared client.
    """
    return default_client().harmonics(payload, **fields)


def health(*args: Any, **kwargs: Any) -> Result:
    """Service health check.

    Forwards to :meth:`AstroMansion.health` on the shared client.
    """
    return default_client().health(*args, **kwargs)


def heliacal(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Heliacal rising and setting events.

    Forwards to :meth:`AstroMansion.heliacal` on the shared client.
    """
    return default_client().heliacal(payload, **fields)


def heliocentric(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Heliocentric positions.

    Forwards to :meth:`AstroMansion.heliocentric` on the shared client.
    """
    return default_client().heliocentric(payload, **fields)


def horary(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Horary question chart.

    Forwards to :meth:`AstroMansion.horary` on the shared client.
    """
    return default_client().horary(payload, **fields)


def list_jobs(*args: Any, **kwargs: Any) -> Result:
    """List jobs.

    Forwards to :meth:`AstroMansion.list_jobs` on the shared client.
    """
    return default_client().list_jobs(*args, **kwargs)


def submit_job(*args: Any, **kwargs: Any) -> Result:
    """Create an async job for any technique.

    Forwards to :meth:`AstroMansion.submit_job` on the shared client.
    """
    return default_client().submit_job(*args, **kwargs)


def submit_batch_job(*args: Any, **kwargs: Any) -> Result:
    """Create an async job batch of up to 20 items.

    Forwards to :meth:`AstroMansion.submit_batch_job` on the shared client.
    """
    return default_client().submit_batch_job(*args, **kwargs)


def job(*args: Any, **kwargs: Any) -> Result:
    """Inspect job status.

    Forwards to :meth:`AstroMansion.job` on the shared client.
    """
    return default_client().job(*args, **kwargs)


def lunar_return(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Lunar return charts.

    Forwards to :meth:`AstroMansion.lunar_return` on the shared client.
    """
    return default_client().lunar_return(payload, **fields)


def mansions(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Twenty-eight lunar mansions.

    Forwards to :meth:`AstroMansion.mansions` on the shared client.
    """
    return default_client().mansions(payload, **fields)


def midpoints(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Planetary midpoints.

    Forwards to :meth:`AstroMansion.midpoints` on the shared client.
    """
    return default_client().midpoints(payload, **fields)


def moon_phases(*args: Any, **kwargs: Any) -> Result:
    """Lunar phase calendar.

    Forwards to :meth:`AstroMansion.moon_phases` on the shared client.
    """
    return default_client().moon_phases(*args, **kwargs)


def moon_phases_for(*args: Any, **kwargs: Any) -> Result:
    """Lunar phase query filtered by month and phase.

    Forwards to :meth:`AstroMansion.moon_phases_for` on the shared client.
    """
    return default_client().moon_phases_for(*args, **kwargs)


def nakshatra(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Moon nakshatra, pada, and ruler.

    Forwards to :meth:`AstroMansion.nakshatra` on the shared client.
    """
    return default_client().nakshatra(payload, **fields)


def natal(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Free natal chart.

    Forwards to :meth:`AstroMansion.natal` on the shared client.
    """
    return default_client().natal(payload, **fields)


def navamsa(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """D9 Navamsa and other divisional charts.

    Forwards to :meth:`AstroMansion.navamsa` on the shared client.
    """
    return default_client().navamsa(payload, **fields)


def pair_aspects(
    birth: dict[str, Any], partner: dict[str, Any], **kwargs: Any
) -> Result:
    """Aspects between two charts.

    Forwards to :meth:`AstroMansion.pair_aspects` on the shared client.
    """
    return default_client().pair_aspects(birth, partner, **kwargs)


def parans(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Fixed-star parans.

    Forwards to :meth:`AstroMansion.parans` on the shared client.
    """
    return default_client().parans(payload, **fields)


def patterns(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Jones patterns, stelliums, and aspect figures.

    Forwards to :meth:`AstroMansion.patterns` on the shared client.
    """
    return default_client().patterns(payload, **fields)


def profection(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Annual profections.

    Forwards to :meth:`AstroMansion.profection` on the shared client.
    """
    return default_client().profection(payload, **fields)


def progression(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Secondary progressions.

    Forwards to :meth:`AstroMansion.progression` on the shared client.
    """
    return default_client().progression(payload, **fields)


def query(*args: Any, **kwargs: Any) -> Result:
    """MansionSQL query over a calculated chart.

    Forwards to :meth:`AstroMansion.query` on the shared client.
    """
    return default_client().query(*args, **kwargs)


def rectification(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Birth-time rectification.

    Forwards to :meth:`AstroMansion.rectification` on the shared client.
    """
    return default_client().rectification(payload, **fields)


def render_astrocartography(*args: Any, **kwargs: Any) -> bytes | Path:
    """Astrocartography map with line meanings.

    Forwards to :meth:`AstroMansion.render_astrocartography` on the shared client.
    """
    return default_client().render_astrocartography(*args, **kwargs)


def render_biwheel(
    birth: dict[str, Any], partner: dict[str, Any], **kwargs: Any
) -> bytes | Path:
    """Bi-wheel chart (natal and second chart).

    Forwards to :meth:`AstroMansion.render_biwheel` on the shared client.
    """
    return default_client().render_biwheel(birth, partner, **kwargs)


def render_png(payload: dict[str, Any] | None = None, **fields: Any) -> bytes | Path:
    """Chart wheel PNG image.

    Forwards to :meth:`AstroMansion.render_png` on the shared client.
    """
    return default_client().render_png(payload, **fields)


def render_sharecard(*args: Any, **kwargs: Any) -> bytes | Path:
    """Story card, natal or synastry (1080x1920).

    Forwards to :meth:`AstroMansion.render_sharecard` on the shared client.
    """
    return default_client().render_sharecard(*args, **kwargs)


def render_svg(payload: dict[str, Any] | None = None, **fields: Any) -> bytes | Path:
    """Chart wheel SVG with optional interactive HTML.

    Forwards to :meth:`AstroMansion.render_svg` on the shared client.
    """
    return default_client().render_svg(payload, **fields)


def retrogrades(*args: Any, **kwargs: Any) -> Result:
    """Planetary retrograde calendar.

    Forwards to :meth:`AstroMansion.retrogrades` on the shared client.
    """
    return default_client().retrogrades(*args, **kwargs)


def saturn_return(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Saturn return dates.

    Forwards to :meth:`AstroMansion.saturn_return` on the shared client.
    """
    return default_client().saturn_return(payload, **fields)


def solar_arc(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Solar arc directions.

    Forwards to :meth:`AstroMansion.solar_arc` on the shared client.
    """
    return default_client().solar_arc(payload, **fields)


def solar_return(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Solar return chart.

    Forwards to :meth:`AstroMansion.solar_return` on the shared client.
    """
    return default_client().solar_return(payload, **fields)


def stations(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Planetary stations and retrograde shadows.

    Forwards to :meth:`AstroMansion.stations` on the shared client.
    """
    return default_client().stations(payload, **fields)


def synastry(birth: dict[str, Any], partner: dict[str, Any], **kwargs: Any) -> Result:
    """Two-chart synastry analysis.

    Forwards to :meth:`AstroMansion.synastry` on the shared client.
    """
    return default_client().synastry(birth, partner, **kwargs)


def timeline(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Life timing timeline.

    Forwards to :meth:`AstroMansion.timeline` on the shared client.
    """
    return default_client().timeline(payload, **fields)


def transit_hits(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Exact aspect times with bisection precision.

    Forwards to :meth:`AstroMansion.transit_hits` on the shared client.
    """
    return default_client().transit_hits(payload, **fields)


def transits(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Transit scan over a year or date range.

    Forwards to :meth:`AstroMansion.transits` on the shared client.
    """
    return default_client().transits(payload, **fields)


def vedic_chart(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Sidereal Vedic chart with rashi, nakshatra, and lagna.

    Forwards to :meth:`AstroMansion.vedic_chart` on the shared client.
    """
    return default_client().vedic_chart(payload, **fields)


def vimshottari(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Vimshottari dasha periods.

    Forwards to :meth:`AstroMansion.vimshottari` on the shared client.
    """
    return default_client().vimshottari(payload, **fields)


def void_moon(*args: Any, **kwargs: Any) -> Result:
    """Void-of-course Moon calendar.

    Forwards to :meth:`AstroMansion.void_moon` on the shared client.
    """
    return default_client().void_moon(*args, **kwargs)


def zodiacal_releasing(payload: dict[str, Any] | None = None, **fields: Any) -> Result:
    """Zodiacal releasing.

    Forwards to :meth:`AstroMansion.zodiacal_releasing` on the shared client.
    """
    return default_client().zodiacal_releasing(payload, **fields)
